mindee/mindee-api-ruby

CHANGELOG.md
lib/mindee/fields/custom_docs.rb
lib/mindee/version.rb
spec/documents_spec.rb

:bug: Fix for missing attribute accessor
Add unit tests on attribute accessors.

version 1.1.1

---

CONTRIBUTING.md

:memo: add contributing guide

---

.github/workflows/test.yml
Gemfile
mindee.gemspec

Switch to Origamindee for Ruby 3 support.

:arrow_up: switch to origamindee

---

bin/mindee.rb
lib/mindee/client.rb
lib/mindee/parsing/prediction.rb
lib/mindee/parsing/prediction/proof_of_address/proof_of_address_v1.rb
spec/data.rb
spec/document/documents_spec.rb

Add proof of address v1 support
Added unit tests

Add proof of address

---

lib/mindee/client.rb
lib/mindee/document_config.rb

Simplify the code around endpoints and document config.

:recycle: only one endpoint possible for a document

---

.github/workflows/docs.yml
.github/workflows/linting.yml
.github/workflows/test-code-samples.yml
.yardopts
README.md
Rakefile
docs/code_samples/bank_account_details_v1.txt
docs/code_samples/bank_check_v1.txt
docs/code_samples/carte_vitale_v1.txt
docs/code_samples/custom_v1.txt
docs/code_samples/default.txt
docs/code_samples/expense_receipts_v4.txt
docs/code_samples/financial_document_v1.txt
docs/code_samples/idcard_fr_v1.txt
docs/code_samples/invoices_v4.txt
docs/code_samples/license_plates_v1.txt
docs/code_samples/passport_v1.txt
docs/code_samples/proof_of_address_v1.txt
docs/code_samples/shipping_containers_v1.txt
docs/ruby-getting-started.md
spec/test_code_samples.sh

Publish documentation to GitHub pages.

:memo: publish documentation

---

lib/mindee/parsing/prediction/common_fields/locale.rb
lib/mindee/parsing/prediction/eu/license_plate/license_plate_v1.rb
lib/mindee/parsing/prediction/financial_document/financial_document_v1.rb
lib/mindee/parsing/prediction/financial_document/line_item.rb
lib/mindee/parsing/prediction/fr/bank_account_details/bank_account_details_v1.rb
lib/mindee/parsing/prediction/fr/carte_vitale/carte_vitale_v1.rb
lib/mindee/parsing/prediction/fr/id_card/id_card_v1.rb
lib/mindee/parsing/prediction/invoice/invoice_v4.rb
lib/mindee/parsing/prediction/invoice/line_item.rb
lib/mindee/parsing/prediction/proof_of_address/proof_of_address_v1.rb
lib/mindee/parsing/prediction/shipping_container/shipping_container_v1.rb
spec/document/proof_of_address_v1_spec.rb

Some preparation for auto-generated products.
Update document output with latest versions of field descriptions.
Field names were auto-generated from OpenAPI specs, except for line items.

:art: update and improve rST output of documents

---

.rubocop.yml
mindee.gemspec

Some dependencies (looking at you rubocop) don't follow semver and introduce breaking changes in minor versions.

:pushpin: update and be more specific about dependencies

---

.rubocop.yml
lib/mindee/parsing/prediction/.rubocop.yml
lib/mindee/parsing/prediction/common_fields/base.rb
lib/mindee/parsing/prediction/common_fields/tax.rb
lib/mindee/parsing/prediction/financial_document/financial_document_v1.rb
lib/mindee/parsing/prediction/financial_document/financial_document_v1_line_item.rb
lib/mindee/parsing/prediction/invoice/invoice_v4.rb
lib/mindee/parsing/prediction/receipt/receipt_v4.rb
lib/mindee/parsing/prediction/receipt/receipt_v5.rb
lib/mindee/parsing/prediction/receipt/receipt_v5_line_item.rb

* Update financial doc v1.1
* Update receipt v5

fixed finanicial doc class to match new tests

---

.github/workflows/linting.yml
.yardopts

Check that the documentation is generated without warnings.

:white_check_mark: check the document generation on push

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.0.0

---

lib/mindee/parsing/standard/position_field.rb
lib/mindee/product/us/bank_check/bank_check_v1.rb
lib/mindee/product/us/bank_check/bank_check_v1_document.rb
lib/mindee/product/us/bank_check/bank_check_v1_page.rb
spec/document/us/bank_check_v1_spec.rb

:arrow_up: update bank-checks & test-lib

---

lib/mindee/http/endpoint.rb
lib/mindee/parsing/common/document.rb

- :bug: fix raw ocr not being created properly from documents
- :recycle:  updated syntax for form params to allow for more coherent use

:bug: fix raw ocr & url source syntax

---

lib/mindee/input/sources.rb
spec/input/files_handling_spec.rb

mimetype hotfix

---

docs/code_samples/invoice_splitter_v1_async.txt
lib/mindee/client.rb

* :sparkles: add asynchronous auto-polling calls

:sparkles: add async auto-polling

---

spec/client_spec.rb
spec/document/custom_v1_spec.rb
spec/document/eu/license_plate_v1_spec.rb
spec/document/financial_document_v1_spec.rb
spec/document/fr/bank_account_details_v1_spec.rb
spec/document/fr/bank_account_details_v2_spec.rb
spec/document/fr/carte_vitale_v1_spec.rb
spec/document/fr/id_card_v1_spec.rb
spec/document/invoice_splitter_v1_spec.rb
spec/document/invoice_v4_spec.rb
spec/document/passport_v1_spec.rb
spec/document/proof_of_address_v1_spec.rb
spec/document/receipt_v4_spec.rb
spec/document/receipt_v5_spec.rb
spec/document/us/bank_check_v1_spec.rb
spec/document/us/driver_license_v1_spec.rb
spec/input/files_handling_spec.rb
spec/input/pdf_processing_spec.rb
spec/input/sources_spec.rb
spec/ocr_spec.rb
spec/test_code_samples.sh

* :arrow_up: update testing lib to latest version & update unit tests

Update test lib

---

README.md
bin/mindee.rb
lib/mindee/client.rb

* :sparkles: add support for async
:bug: fix async calls not polling more than once

:sparkles: add support for async in CLI

---

docs/barcode_reader_v1.md
docs/code_samples/barcode_reader_v1.txt
lib/mindee/product.rb
lib/mindee/product/barcode_reader/barcode_reader_v1.rb
lib/mindee/product/barcode_reader/barcode_reader_v1_document.rb
lib/mindee/product/barcode_reader/barcode_reader_v1_page.rb
spec/document/barcode_reader_v1_spec.rb

:sparkles: add support for barcode reader

---

docs/code_samples/cropper_v1.txt
docs/cropper_v1.md
docs/financial_document_v1.md
lib/mindee/geometry/quadrilateral.rb
lib/mindee/parsing/standard/company_registration_field.rb
lib/mindee/product/cropper/cropper_v1.rb
lib/mindee/product/financial_document/financial_document_v1_document.rb
lib/mindee/product/invoice/invoice_v4_document.rb
lib/mindee/product/proof_of_address/proof_of_address_v1_document.rb
lib/mindee/product/receipt/receipt_v5_document.rb

* :recycle: changed `CompanyRegistration` to `CompanyRegistrationField`

:recycle: refacto

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.2.0

---

bin/mindee.rb

:wrench: hotfix CLI script

---

lib/mindee/parsing/common/api_response.rb
lib/mindee/parsing/common/document.rb
spec/api_response_spec.rb
spec/async_rseponse_spec.rb

:sparkles: add access to  document property

---

lib/mindee/http/endpoint.rb
spec/http/endpoint_spec.rb

* :wrench: add access to url root to help address issues like #67

:wrench: add access to root url for testing purposes

---

CHANGELOG.md
docs/custom_v1.md
lib/mindee/version.rb

:bookmark: version 3.3.0

---

docs/bank_account_details_v2.md
docs/bank_check_v1.md
docs/barcode_reader_v1.md
docs/carte_grise_v1.md
docs/carte_vitale_v1.md
docs/cropper_v1.md
docs/expense_receipts_v5.md
docs/financial_document_v1.md
docs/idcard_fr_v2.md
docs/invoices_v4.md
docs/license_plates_v1.md
docs/multi_receipts_detector_v1.md
docs/passport_v1.md
docs/proof_of_address_v1.md
docs/us_driver_license_v1.md
docs/us_w9_v1.md
lib/mindee/client.rb

:arrow_up: fix async values

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.3.1

---

docs/invoices_v4.md
lib/mindee/parsing/standard/string_field.rb
lib/mindee/product/invoice/invoice_v4_document.rb
spec/document/invoice_v4_spec.rb
spec/fields/string_field_spec.rb

* :arrow_up: update invoice to v4.4
* :arrow_up: update tests
* :arrow_up: update test lib
* :memo: update doc

:arrow_up: update invoice to v4.4

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.4.0

---

docs/code_samples/default_async.txt
spec/test_code_samples.sh

* :memo: add missing default async sample code

:memo: add default async sample code

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.5.0

---

docs/eu_driver_license_v1.md
docs/international_id_v2.md
lib/mindee/product/eu/driver_license/driver_license_v1.rb
lib/mindee/product/eu/driver_license/driver_license_v1_document.rb
lib/mindee/product/eu/driver_license/driver_license_v1_page.rb
spec/document/eu/driver_license_v1_spec.rb

:memo: fix eudl doc + add missing entry for international id v2

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.6.0

---

lib/mindee/http/endpoint.rb
lib/mindee/http/error.rb
lib/mindee/http/response_validation.rb
lib/mindee/parsing/common/api_response.rb
spec/async_rseponse_spec.rb
spec/http/error_spec.rb
spec/http/mock_http_response.rb

:recycle: upate error handling

---

README.md
docs/international_id_v2.md

:recycle: update test lib + update doc

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.6.1

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.7.0

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.8.0

---

.rubocop.yml
docs/expense_receipts_v5.md
docs/financial_document_v1.md
lib/mindee/product/financial_document/financial_document_v1_document.rb
lib/mindee/product/financial_document/financial_document_v1_page.rb
lib/mindee/product/receipt/receipt_v5_document.rb
lib/mindee/product/receipt/receipt_v5_page.rb
spec/document/financial_document_v1_spec.rb

* :sparkles: update receipt API to v5.2
* :sparkles: update financial doc API to 1.7
* :recycle: update test lib

:sparkles: update financial document to 1.7 & receipt to 5.2

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.9.0

---

lib/mindee/client.rb
lib/mindee/input/local_response.rb
lib/mindee/input/sources.rb
lib/mindee/parsing/common/api_response.rb
spec/client_spec.rb
spec/input/local_response_spec.rb

* :sparkles: add webhooks
* :sparkles: add local response loading

:sparkles: add webhooks

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.10.0

---

lib/mindee/parsing/standard/company_registration_field.rb

* :recycle: add type on company registration print

:recycle: update display for company registration fields

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: version 3.12.0

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 3.13.0

---

examples/auto_multi_receipts_detector_extraction.rb

:memo: fix multi receipts auto-extractionexample script

---

docs/bill_of_lading_v1.md
docs/energy_bill_fra_v1.md
docs/expense_receipts_v5.md
docs/financial_document_v1.md
docs/invoices_v4.md
docs/nutrition_facts_v1.md
docs/payslip_fra_v2.md
docs/us_mail_v2.md
lib/mindee/parsing/standard/date_field.rb
lib/mindee/product/financial_document/financial_document_v1_document.rb
lib/mindee/product/financial_document/financial_document_v1_page.rb
lib/mindee/product/invoice/invoice_v4_document.rb
lib/mindee/product/invoice/invoice_v4_page.rb
spec/fields/date_field_spec.rb

:sparkles: add support for financial document v1.10 & invoice v4.8

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 3.14.0

---

lib/mindee.rb
lib/mindee/client.rb
lib/mindee/extraction/common/extracted_image.rb
lib/mindee/extraction/common/image_extractor.rb
lib/mindee/extraction/pdf_extractor/pdf_extractor.rb
lib/mindee/extraction/tax_extractor/tax_extractor.rb
lib/mindee/geometry/point.rb
lib/mindee/image.rb
lib/mindee/image/image_compressor.rb
lib/mindee/image/image_utils.rb
lib/mindee/input/sources.rb
lib/mindee/parsing/standard/position_field.rb
lib/mindee/pdf.rb
lib/mindee/pdf/pdf_compressor.rb
lib/mindee/pdf/pdf_processor.rb
lib/mindee/pdf/pdf_tools.rb
mindee.gemspec
spec/input/sources_spec.rb

* :sparkles: add support for image compression
* :sparkles: add support for PDF compression
* :recycle: refactor pdf & image namespaces
* :memo: fix rubocop directives unexpectedly appearing in Yard documentation

:sparkles: add support for image & PDF compression

---

lib/mindee/image/image_utils.rb
lib/mindee/pdf/pdf_tools.rb
mindee.gemspec
spec/input/sources_spec.rb

* :arrow_up: bump mini_magick to 5.0.1
* :recycle: fix typos etc.

:recycle: fix typos & bump minimagick

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 3.15.0

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 3.16.0

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 3.17.0

---

lib/mindee/extraction/tax_extractor/tax_extractor.rb

:bug: fix tax extractor script

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 3.19.0

---

lib/mindee/parsing/common/document.rb
spec/extras/full_text_ocr_spec.rb

:bug: fix extras failing at document level if missing from prediction

---

CHANGELOG.md
README.md
lib/mindee/version.rb

:bookmark: Version 3.19.1

---

.github/workflows/_publish-code.yml
.github/workflows/_publish-docs.yml
.github/workflows/_publish-guide.yml
.github/workflows/_static-analysis.yml
.github/workflows/_test-code-samples.yml
.github/workflows/_test-integrations.yml
.github/workflows/_test-units.yml
.github/workflows/cron.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/push-main-branch.yml

- :recycle: harmonize gh CI with new SDK syntax.

:recycle: harmonize GH CI

---

lib/mindee.rb
lib/mindee/client.rb
lib/mindee/http/endpoint.rb
lib/mindee/http/workflow_endpoint.rb
lib/mindee/image/extracted_image.rb
lib/mindee/input/sources/base64_input_source.rb
lib/mindee/input/sources/local_input_source.rb
lib/mindee/input/sources/url_input_source.rb
lib/mindee/logging.rb
lib/mindee/logging/logger.rb
lib/mindee/parsing/common/api_response.rb
lib/mindee/pdf/pdf_compressor.rb
spec/client_spec.rb
spec/input/sources/files_handling_spec.rb
spec/input/sources/sources_spec.rb

:sparkles: add support for logging

---

examples/auto_invoice_splitter_extraction.rb
lib/mindee.rb
lib/mindee/client.rb
lib/mindee/extraction/multi_receipts_extractor.rb
lib/mindee/image/image_extractor.rb
lib/mindee/input/sources/local_input_source.rb
lib/mindee/parsing/common/document.rb
lib/mindee/parsing/common/execution_priority.rb
lib/mindee/parsing/common/extras/cropper_extra.rb
lib/mindee/parsing/common/extras/extras.rb
lib/mindee/parsing/common/extras/full_text_ocr_extra.rb
lib/mindee/parsing/standard/base_field.rb
lib/mindee/parsing/standard/boolean_field.rb
lib/mindee/parsing/standard/company_registration_field.rb
lib/mindee/pdf/pdf_compressor.rb
lib/mindee/pdf/pdf_tools.rb
spec/extraction/multi_receipts_extractor_spec.rb

:memo: fix missing yard documentation + micro-refacto

---

lib/mindee/parsing/universal/universal_object_field.rb
sig/mindee/parsing/standard/position_field.rbs
sig/mindee/parsing/universal/universal_list_field.rbs
sig/mindee/parsing/universal/universal_object_field.rbs
spec/document/universal_spec.rb
spec/extraction/invoice_splitter_extraction_integration.rb
spec/extras/full_text_ocr_spec.rb
spec/image/image_utils_spec.rb
spec/input/sources/url_input_source_integration.rb
spec/input/sources/url_input_source_spec.rb
spec/parsing/universal/universal_list_field_spec.rb
spec/parsing/universal/universal_object_field_spec.rb
spec/pdf/extracted_pdf_spec.rb
spec/pdf/pdf_extractor_spec.rb

* :bug: fix position fields not being properly initialized in universal products
* :recycle: add tests for universal fields
* :recycle: add proper typing for universal fields
* :recycle: cleanup some test syntaxes

:bug: fix universal product broken positions + add tests

---

lib/mindee/logging/logger.rb

:bug: set default logger level to warn

---

lib/mindee/client.rb
lib/mindee/http/endpoint.rb
lib/mindee/http/workflow_endpoint.rb
lib/mindee/input/sources/url_input_source.rb
sig/mindee/client.rbs
sig/mindee/input/sources/url_input_source.rbs
spec/input/sources/url_input_source_integration.rb
spec/input/sources/url_input_source_spec.rb

:recycle: update `UrlInputSource` to `URLInputSource`

---

.github/workflows/_test-code-samples.yml
.github/workflows/_test-integrations.yml
.github/workflows/_test-units.yml
README.md
mindee.gemspec

* :arrow_up: bump origamindee dependency
* :arrow_up: add base64 external dependency for ruby 3.4

:recycle: add support for ruby 3.4

---

.github/workflows/_publish-code.yml
.github/workflows/_static-analysis.yml
.github/workflows/_test-code-samples.yml
.github/workflows/_test-integrations.yml
.github/workflows/_test-units.yml

Note: will break CI on main for 1 commit

:arrow_up: setup CI for v4

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 4.0.0

---

.github/workflows/_publish-code.yml

:bug: fix publish action

---

docs/advanced_file_operations.md
docs/code_samples/workflow_execution.txt
docs/loading_a_document.md
lib/mindee/client.rb
lib/mindee/http/workflow_endpoint.rb
sig/custom/net_http.rbs
sig/mindee/client.rbs
sig/mindee/http/workflow_endpoint.rbs
spec/workflow/workflow_integration.rb

* :sparkles: add support for RAG param in workflow execution calls
* :memo: add missing code sample
* :bug: fix invalid typing for workflow executions
* :memo: fix typos in doc

:sparkles: add support for RAG in workflow executions

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 4.1.0

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 4.1.1

---

lib/mindee/geometry/polygon.rb
mindee.gemspec

:wrench: update dependencies & loosen version constraints

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 4.1.2

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 4.3.0

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 4.4.0

---

docs/global_products/expense_receipts_v5.md
docs/global_products/financial_document_v1.md
docs/global_products/international_id_v2.md
docs/global_products/invoice_splitter_v1.md
docs/global_products/invoices_v4.md
docs/localized_products/energy_bill_fra_v1.md
docs/localized_products/ind_passport_v1.md
docs/localized_products/us_healthcare_cards_v1.md
docs/localized_products/us_mail_v3.md
lib/mindee/parsing/common/inference.rb
lib/mindee/product/financial_document/financial_document_v1_document.rb
lib/mindee/product/financial_document/financial_document_v1_page.rb
lib/mindee/product/ind/indian_passport/indian_passport_v1_document.rb
lib/mindee/product/international_id/international_id_v2_document.rb
lib/mindee/product/international_id/international_id_v2_page.rb
lib/mindee/product/invoice/invoice_v4_document.rb
lib/mindee/product/invoice/invoice_v4_page.rb
lib/mindee/product/invoice_splitter/invoice_splitter_v1_document.rb
lib/mindee/product/invoice_splitter/invoice_splitter_v1_page.rb
lib/mindee/product/receipt/receipt_v5_document.rb
lib/mindee/product/receipt/receipt_v5_page.rb
lib/mindee/product/us/healthcare_card/healthcare_card_v1_copay.rb
lib/mindee/product/us/healthcare_card/healthcare_card_v1_copays.rb
lib/mindee/product/us/healthcare_card/healthcare_card_v1_document.rb
lib/mindee/product/us/healthcare_card/healthcare_card_v1_page.rb
sig/mindee/product/invoice/invoice_v4_document.rbs
sig/mindee/product/us/healthcare_card/healthcare_card_v1_document.rbs
spec/api_response_spec.rb

* :sparkles: add support for financial document v1.14, US healthcare cards v1.3 & invoice v4.11
* :recycle: update api call test

:sparkles: add support for financial document v1.14, US healthcare cards v1.3 & invoice v4.11

---

lib/mindee/http/api_settings_v2.rb

:bug: fix user agent not being able to access version number

---

CHANGELOG.md
lib/mindee/version.rb

:bookmark: Version 4.7.0-rc3
